// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJq270z6TXEWC8N6S30oMN-EIsW4gR_NY',
    appId: '1:982037328118:web:ef058295a1ae8cfedbbcd7',
    messagingSenderId: '982037328118',
    projectId: 'cosmic-match-bb93f',
    authDomain: 'cosmic-match-bb93f.firebaseapp.com',
    storageBucket: 'cosmic-match-bb93f.firebasestorage.app',
    measurementId: 'G-7RD0JT2MVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SMaWuqmSEj1Swvd8R0EgErvkaqP0gS8',
    appId: '1:982037328118:android:346b666b0f0fe014dbbcd7',
    messagingSenderId: '982037328118',
    projectId: 'cosmic-match-bb93f',
    storageBucket: 'cosmic-match-bb93f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz7A8jYZYavN0PD8bYiOm0NM3Wop7oUuc',
    appId: '1:982037328118:ios:f66f279c4be30894dbbcd7',
    messagingSenderId: '982037328118',
    projectId: 'cosmic-match-bb93f',
    storageBucket: 'cosmic-match-bb93f.firebasestorage.app',
    iosBundleId: 'com.cosmicmatch.cosmicMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz7A8jYZYavN0PD8bYiOm0NM3Wop7oUuc',
    appId: '1:982037328118:ios:f66f279c4be30894dbbcd7',
    messagingSenderId: '982037328118',
    projectId: 'cosmic-match-bb93f',
    storageBucket: 'cosmic-match-bb93f.firebasestorage.app',
    iosBundleId: 'com.cosmicmatch.cosmicMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJq270z6TXEWC8N6S30oMN-EIsW4gR_NY',
    appId: '1:982037328118:web:30955632492b1ee0dbbcd7',
    messagingSenderId: '982037328118',
    projectId: 'cosmic-match-bb93f',
    authDomain: 'cosmic-match-bb93f.firebaseapp.com',
    storageBucket: 'cosmic-match-bb93f.firebasestorage.app',
    measurementId: 'G-M2EWSDX76B',
  );
}
